spring:
  datasource:
    password: admin
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

my:
  greeting: nice to meet you
  values: one, two, three

my-properties:
  host: google.com
  port: 8080